apiVersion: v1
kind: Pod
metadata: # info about POD
 name: ashupod-1  # name of pod 
 namespace: default # target namespace to deploy 
spec: # info about application 
 containers:
 - name: ashuc1 # name of container 
   image: alpine # docker image
   command: ["sh","-c","ping fb.com"] # default parent process
   # command can replace a process by entrypoint 