apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashudatapod
  name: ashudatapod # name of pod 
spec:
  volumes: # to create data volumes 
  - name: ashuvol1 # name of volume  
    emptyDir: {} # volume type a predefine location will be used to create volume
  containers: # to create containers 
  - image: nginx  # helper container 
    name: ashuc1 
    volumeMounts:
    - name: ashuvol1
      mountPath: /usr/share/nginx/html/
      readOnly: True 
  - image: alpine # data generation container 
    name: ashudatapod
    volumeMounts: # to mount volume we created above 
    - name: ashuvol1
      mountPath: /mnt/oracle/
    command: ["sh","-c","while true;do echo 'hello <input>' >>/mnt/oracle/data.txt;sleep 5;done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
