FROM oraclelinux:8.4
# Image will be pulled from Docker hub if not present 
LABEL name="ashutoshh"
LABEL email="ashutoshh@linux.com"
# optional field 
# sharing image team info 

# updating ubuntu lib
# to give a virtual shell 
RUN yum  install  net-tools -y
# net-tools will give ping command 
